-- grab a picture of assessments, mimicing the warehouse view except for current barrier status.
SELECT
  a.stream_crossing_id,
  a.assessment_id,
  a.submission_id,
  a.structure_id,
  x.external_crossing_reference,
  x.stream_name,
  x.road_name,
  x.road_km_mark,
  str.crossing_type_code,
  str.crossing_subtype_code,
  a.assessment_date,
  a.project_id,
  p.funding_project_number,
  p.funding_source_code,
  p.responsible_party_client_name,
  p.consultant_client_name,
  str.diameter_or_span,
  str.length_or_width,
  a.crew_members,
  a.continuous_embeddedment_ind,
  a.average_depth_embededdment,
  a.resemble_channel_ind,
  a.backwatered_ind,
  a.percentage_backwatered,
  a.fill_depth,
  a.outlet_drop,
  a.outlet_pool_depth,
  a.inlet_drop_ind,
  a.culvert_slope,
  a.downstream_channel_width,
  a.stream_slope,
  a.stream_width_ratio,
  a.beaver_activity_ind,
  a.fish_observed_ind,
  a.valley_fill_code,
  a.habitat_value_code,
  a.embed_score,
  a.culvert_length_score,
  a.outlet_drop_score,
  a.culvert_slope_score,
  a.stream_width_ratio_score,
  a.final_score,
  a.barrier_result_code,
  a.assessment_comment,
  a.crossing_fix_code,
  a.recommended_diameter_or_span,
  'http://a100.gov.bc.ca/pub/pscismap/imageViewer.do?assessmentId='||a.assessment_id as image_view_url,
  'http://a100.gov.bc.ca/pub/acat/public/advancedSearch.do?keywords=[PSCIS'||p.project_id||']&searchKeyType=searchAll&sortColumn=title' as ecocat_url,
  x.geom
FROM pscis.pscis_crossing_assessments a
INNER JOIN pscis.pscis_stream_cross_loc_point x
ON a.stream_crossing_id = x.stream_crossing_id
INNER JOIN pscis.pscis_structures str
ON a.stream_crossing_id = str.stream_crossing_id
INNER JOIN pscis.pscis_projects p
ON a.project_id = p.project_id