DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id in (125337,6823); 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id in (125304,7460); 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id in (3912,4061); 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id in (10365,50461); 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7950; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7950 WHERE stream_crossing_id = 102773; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7856; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7856 WHERE stream_crossing_id = 123266; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7984; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7984 WHERE stream_crossing_id = 102710; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7981; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7981 WHERE stream_crossing_id = 102721; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7936; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7936 WHERE stream_crossing_id = 102761; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7964; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7964 WHERE stream_crossing_id = 102683; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7951; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7951 WHERE stream_crossing_id = 102774; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7949; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7949 WHERE stream_crossing_id = 102775; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7954; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7954 WHERE stream_crossing_id = 102778; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7956; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7956 WHERE stream_crossing_id = 102787; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7957; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7957 WHERE stream_crossing_id = 102793; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 58240; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 58240 WHERE stream_crossing_id = 195334; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 58161; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 58161 WHERE stream_crossing_id = 123432; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 58259; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 58259 WHERE stream_crossing_id = 123620; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3079; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3079 WHERE stream_crossing_id = 195260; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3080; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3080 WHERE stream_crossing_id = 195258; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3093; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3093 WHERE stream_crossing_id = 195254; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7429; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7429 WHERE stream_crossing_id = 6334; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7436; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7436 WHERE stream_crossing_id = 125728; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7439; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7439 WHERE stream_crossing_id = 125737; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7424; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7424 WHERE stream_crossing_id = 7839; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6812; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6812 WHERE stream_crossing_id = 7836; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7433; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7433 WHERE stream_crossing_id = 6814; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7585; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7585 WHERE stream_crossing_id = 7834; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6809; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6809 WHERE stream_crossing_id = 7840; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 76; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 76 WHERE stream_crossing_id = 125598; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57641; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57641 WHERE stream_crossing_id = 125414; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57615; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57615 WHERE stream_crossing_id = 125413; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57699; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57699 WHERE stream_crossing_id = 125416; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57614; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57614 WHERE stream_crossing_id = 125409; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57664; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57664 WHERE stream_crossing_id = 125408; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57631; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57631 WHERE stream_crossing_id = 125412; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57662; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57662 WHERE stream_crossing_id = 125399; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57613; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57613 WHERE stream_crossing_id = 125400; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57653; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57653 WHERE stream_crossing_id = 125405; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57656; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57656 WHERE stream_crossing_id = 125406; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57616; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57616 WHERE stream_crossing_id = 125394; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57619; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57619 WHERE stream_crossing_id = 125392; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57666; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57666 WHERE stream_crossing_id = 125396; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57617; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57617 WHERE stream_crossing_id = 125393; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57618; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57618 WHERE stream_crossing_id = 125391; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57717; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57717 WHERE stream_crossing_id = 125351; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57677; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57677 WHERE stream_crossing_id = 125350; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57667; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57667 WHERE stream_crossing_id = 125398; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6747; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6747 WHERE stream_crossing_id = 6825; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57722; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57722 WHERE stream_crossing_id = 125349; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57621; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57621 WHERE stream_crossing_id = 125385; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57747; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57747 WHERE stream_crossing_id = 125340; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57620; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57620 WHERE stream_crossing_id = 125389; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8119; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8119 WHERE stream_crossing_id = 51599; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57678; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57678 WHERE stream_crossing_id = 125348; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57642; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57642 WHERE stream_crossing_id = 125390; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57643; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57643 WHERE stream_crossing_id = 125388; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57668; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57668 WHERE stream_crossing_id = 125384; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57622; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57622 WHERE stream_crossing_id = 125383; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57680; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57680 WHERE stream_crossing_id = 125346; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57670; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57670 WHERE stream_crossing_id = 125378; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57629; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57629 WHERE stream_crossing_id = 125380; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57633; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57633 WHERE stream_crossing_id = 125370; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57634; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57634 WHERE stream_crossing_id = 125371; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57625; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57625 WHERE stream_crossing_id = 125369; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57626; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57626 WHERE stream_crossing_id = 125367; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57637; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57637 WHERE stream_crossing_id = 125365; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57638; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57638 WHERE stream_crossing_id = 125368; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57640; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57640 WHERE stream_crossing_id = 125364; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6731; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6731 WHERE stream_crossing_id = 124946; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57726; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57726 WHERE stream_crossing_id = 125354; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57720; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57720 WHERE stream_crossing_id = 125260; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57721; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57721 WHERE stream_crossing_id = 125259; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6746; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6746 WHERE stream_crossing_id = 125335; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57684; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57684 WHERE stream_crossing_id = 125360; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57683; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57683 WHERE stream_crossing_id = 125358; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57682; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57682 WHERE stream_crossing_id = 125356; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57737; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57737 WHERE stream_crossing_id = 125357; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7458; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7458 WHERE stream_crossing_id = 125313; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6748; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6748 WHERE stream_crossing_id = 6827; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6739; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6739 WHERE stream_crossing_id = 125305; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6784; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6784 WHERE stream_crossing_id = 126115; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57688; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57688 WHERE stream_crossing_id = 125430; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57689; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57689 WHERE stream_crossing_id = 125429; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6649; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6649 WHERE stream_crossing_id = 5935; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57748; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57748 WHERE stream_crossing_id = 125426; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57690; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57690 WHERE stream_crossing_id = 125417; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6648; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6648 WHERE stream_crossing_id = 5932; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57693; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57693 WHERE stream_crossing_id = 125419; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57694; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57694 WHERE stream_crossing_id = 125421; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57704; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57704 WHERE stream_crossing_id = 124965; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57706; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57706 WHERE stream_crossing_id = 124967; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57707; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57707 WHERE stream_crossing_id = 124968; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57708; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57708 WHERE stream_crossing_id = 124969; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57709; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57709 WHERE stream_crossing_id = 124970; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57710; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57710 WHERE stream_crossing_id = 124971; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57711; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57711 WHERE stream_crossing_id = 124972; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57735; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57735 WHERE stream_crossing_id = 124974; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3972; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3972 WHERE stream_crossing_id = 3604; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57713; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57713 WHERE stream_crossing_id = 124975; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57696; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57696 WHERE stream_crossing_id = 125425; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57715; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57715 WHERE stream_crossing_id = 124976; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6678; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6678 WHERE stream_crossing_id = 6107; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7779; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7779 WHERE stream_crossing_id = 51414; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6699; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6699 WHERE stream_crossing_id = 6092; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6706; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6706 WHERE stream_crossing_id = 5874; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5650; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 5650 WHERE stream_crossing_id = 5649; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6384; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6384 WHERE stream_crossing_id = 126360; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6830; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6830 WHERE stream_crossing_id = 195629; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7378; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7378 WHERE stream_crossing_id = 3024; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7375; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7375 WHERE stream_crossing_id = 3037; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7111; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7111 WHERE stream_crossing_id = 3033; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7112; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7112 WHERE stream_crossing_id = 2944; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6841; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6841 WHERE stream_crossing_id = 195600; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7379; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7379 WHERE stream_crossing_id = 3017; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7372; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7372 WHERE stream_crossing_id = 3029; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57562; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57562 WHERE stream_crossing_id = 126470; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6532; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6532 WHERE stream_crossing_id = 57188; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57172; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57172 WHERE stream_crossing_id = 57174; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57201; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 57201 WHERE stream_crossing_id = 124349; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7657; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7657 WHERE stream_crossing_id = 5551; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6401; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6401 WHERE stream_crossing_id = 250; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6399; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6399 WHERE stream_crossing_id = 251; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6402; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6402 WHERE stream_crossing_id = 249; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3970; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3970 WHERE stream_crossing_id = 3605; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7605; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7605 WHERE stream_crossing_id = 4905; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7614; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7614 WHERE stream_crossing_id = 4924; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7613; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7613 WHERE stream_crossing_id = 4923; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7612; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7612 WHERE stream_crossing_id = 4922; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3285; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3285 WHERE stream_crossing_id = 5073; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6460; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 6460 WHERE stream_crossing_id = 7675; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7481; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7481 WHERE stream_crossing_id = 4758; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7479; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7479 WHERE stream_crossing_id = 4782; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7477; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7477 WHERE stream_crossing_id = 4699; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7476; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7476 WHERE stream_crossing_id = 4691; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7535; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7535 WHERE stream_crossing_id = 4696; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7472; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7472 WHERE stream_crossing_id = 4686; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7533; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7533 WHERE stream_crossing_id = 4697; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7468; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7468 WHERE stream_crossing_id = 4693; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3317; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3317 WHERE stream_crossing_id = 4795; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3318; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3318 WHERE stream_crossing_id = 4800; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4836; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 4836 WHERE stream_crossing_id = 7491; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7492; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7492 WHERE stream_crossing_id = 4837; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3446; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3446 WHERE stream_crossing_id = 7654; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7785; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7785 WHERE stream_crossing_id = 51569; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7787; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7787 WHERE stream_crossing_id = 51567; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7782; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7782 WHERE stream_crossing_id = 51394; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5083; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 5083 WHERE stream_crossing_id = 3752; 
UPDATE pscis.pscis_assessment_svw SET current_pscis_status = 'DESIGN' WHERE stream_crossing_id = 5083; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8129; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8129 WHERE stream_crossing_id = 51596; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5082; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 5082 WHERE stream_crossing_id = 3751; 
UPDATE pscis.pscis_assessment_svw SET current_pscis_status = 'DESIGN' WHERE stream_crossing_id = 5082; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5081; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 5081 WHERE stream_crossing_id = 3750; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8138; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8138 WHERE stream_crossing_id = 51027; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5080; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 5080 WHERE stream_crossing_id = 3749; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3572; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3572 WHERE stream_crossing_id = 4993; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3395; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3395 WHERE stream_crossing_id = 8021; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3573; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3573 WHERE stream_crossing_id = 4994; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3397; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3397 WHERE stream_crossing_id = 8023; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8114; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8114 WHERE stream_crossing_id = 50835; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7777; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7777 WHERE stream_crossing_id = 51419; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3582; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3582 WHERE stream_crossing_id = 5003; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8131; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8131 WHERE stream_crossing_id = 51594; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7794; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7794 WHERE stream_crossing_id = 51590; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7781; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7781 WHERE stream_crossing_id = 51401; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7796; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7796 WHERE stream_crossing_id = 51588; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7797; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7797 WHERE stream_crossing_id = 50789; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3300; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3300 WHERE stream_crossing_id = 7681; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7798; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7798 WHERE stream_crossing_id = 51585; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7799; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7799 WHERE stream_crossing_id = 51582; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7813; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7813 WHERE stream_crossing_id = 51026; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7727; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7727 WHERE stream_crossing_id = 63159; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8035; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8035 WHERE stream_crossing_id = 63156; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8027; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8027 WHERE stream_crossing_id = 63085; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50510; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50510 WHERE stream_crossing_id = 62603; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8028; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8028 WHERE stream_crossing_id = 63087; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3883; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3883 WHERE stream_crossing_id = 7695; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3875; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3875 WHERE stream_crossing_id = 8037; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3877; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3877 WHERE stream_crossing_id = 8041; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3906; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3906 WHERE stream_crossing_id = 8039; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3891; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 3891 WHERE stream_crossing_id = 7729; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7742; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7742 WHERE stream_crossing_id = 112300; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7743; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7743 WHERE stream_crossing_id = 112307; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50479; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50479 WHERE stream_crossing_id = 103104; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8058; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8058 WHERE stream_crossing_id = 112279; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8057; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8057 WHERE stream_crossing_id = 112288; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7745; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7745 WHERE stream_crossing_id = 112281; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7746; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7746 WHERE stream_crossing_id = 112276; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7738; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 7738 WHERE stream_crossing_id = 112264; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50471; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50471 WHERE stream_crossing_id = 103099; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50472; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50472 WHERE stream_crossing_id = 103096; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50469; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50469 WHERE stream_crossing_id = 103076; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50473; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50473 WHERE stream_crossing_id = 103078; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 61184; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 61184 WHERE stream_crossing_id = 61183; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50466; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50466 WHERE stream_crossing_id = 103071; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50465; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50465 WHERE stream_crossing_id = 103062; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50463; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50463 WHERE stream_crossing_id = 103060; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50460; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50460 WHERE stream_crossing_id = 103066; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50528; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50528 WHERE stream_crossing_id = 62572; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50531; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50531 WHERE stream_crossing_id = 62575; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50509; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50509 WHERE stream_crossing_id = 62602; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50505; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50505 WHERE stream_crossing_id = 62601; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50506; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50506 WHERE stream_crossing_id = 62600; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50503; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50503 WHERE stream_crossing_id = 62604; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50515; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50515 WHERE stream_crossing_id = 62608; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50535; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50535 WHERE stream_crossing_id = 62599; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50497; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50497 WHERE stream_crossing_id = 62593; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50500; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50500 WHERE stream_crossing_id = 62595; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50498; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50498 WHERE stream_crossing_id = 62594; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8095; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 8095 WHERE stream_crossing_id = 50561; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50161; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50161 WHERE stream_crossing_id = 62508; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50158; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50158 WHERE stream_crossing_id = 62513; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50154; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50154 WHERE stream_crossing_id = 62519; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62161; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 62161 WHERE stream_crossing_id = 62160; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50185; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50185 WHERE stream_crossing_id = 103036; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50180; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50180 WHERE stream_crossing_id = 103034; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50188; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50188 WHERE stream_crossing_id = 103049; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50191; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50191 WHERE stream_crossing_id = 103053; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50192; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50192 WHERE stream_crossing_id = 103054; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50193; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50193 WHERE stream_crossing_id = 103048; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50197; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50197 WHERE stream_crossing_id = 103046; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50198; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50198 WHERE stream_crossing_id = 103030; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50199; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50199 WHERE stream_crossing_id = 103041; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50200; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50200 WHERE stream_crossing_id = 103031; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50251; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50251 WHERE stream_crossing_id = 102979; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50221; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50221 WHERE stream_crossing_id = 102969; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50238; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50238 WHERE stream_crossing_id = 62489; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50216; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50216 WHERE stream_crossing_id = 103002; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50256; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50256 WHERE stream_crossing_id = 103020; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50271; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50271 WHERE stream_crossing_id = 102975; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50253; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50253 WHERE stream_crossing_id = 102973; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50254; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50254 WHERE stream_crossing_id = 103016; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50259; 
UPDATE pscis.pscis_assessment_svw SET stream_crossing_id = 50259 WHERE stream_crossing_id = 103021; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3237; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123252; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123313; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123253; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123254; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123245; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123242; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123250; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123243; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123251; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123241; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123240; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123247; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123246; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123249; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123248; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123324; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123320; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102684; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123244; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8323; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8445; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102362; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124431; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124473; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123562; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195357; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123638; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2917; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195464; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123443; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57771; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195291; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123652; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 1417; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4261; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4259; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4245; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4236; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4237; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4123; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4187; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4161; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4169; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4170; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102820; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 125820; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4041; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4040; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124711; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124710; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4031; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4032; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 125514; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 1176; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 1181; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 1190; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124637; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 69265; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 69240; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 65; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 67; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 72; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195757; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 125377; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 125376; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 52020; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124863; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 54090; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 68072; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5936; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195711; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195592; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5933; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5907; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5903; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195736; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195710; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 125561; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195709; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195737; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195708; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195702; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195700; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195703; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195701; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51982; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195738; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195734; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195704; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195735; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195731; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195739; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195730; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195707; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195723; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195733; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195706; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195732; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195705; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6091; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 6183; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195724; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195727; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195715; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195725; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195713; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195716; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195726; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195714; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195728; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195729; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51952; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51946; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51928; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195722; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51479; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195751; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195719; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195750; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195717; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195718; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195740; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51457; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195749; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195741; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195748; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195777; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195747; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195742; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195744; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195720; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195776; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195778; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195745; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195721; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195779; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195746; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195743; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195775; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195774; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195780; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195759; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195758; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195752; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195753; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195754; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195755; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2967; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195812; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195781; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195811; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195782; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195783; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195784; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195785; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195772; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5295; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195813; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195805; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3020; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195771; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3026; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195770; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195804; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195769; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195802; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195766; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195773; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195801; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195803; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2957; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195756; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195768; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195810; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195786; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195809; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195807; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195806; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2961; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2962; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195790; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195800; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195799; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195808; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195767; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195798; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195765; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195797; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195787; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195792; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195788; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195794; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195796; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195763; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195795; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195764; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195789; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195791; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195793; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195760; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57602; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195762; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 195761; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2977; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 2986; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4075; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5343; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 1582; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5351; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124308; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5371; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5429; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8193; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5406; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8183; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57511; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124099; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8179; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8178; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57343; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57345; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57113; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57295; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 1583; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123959; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 123956; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57289; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 57233; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 124344; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 239; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 248; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 217; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 218; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 229; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 226; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 227; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 254; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 234; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 220; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 209; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 259; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 257; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3643; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5007; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3574; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3971; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50917; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 201; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 63383; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62974; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62948; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62949; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102072; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102032; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102029; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7728; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102020; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102021; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102017; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 7711; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 524; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50667; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5102; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5103; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 61237; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5111; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51302; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5149; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5150; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4058; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 4059; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 5215; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 8055; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 3835; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62454; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 112225; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 112230; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51222; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51201; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51200; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51199; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62280; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51198; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51197; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51195; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51196; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51194; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51193; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51192; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51226; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62171; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51225; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51220; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 61490; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51249; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51250; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51227; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51221; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51228; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51229; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51218; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51230; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51247; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51248; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51219; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51217; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51273; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51231; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51216; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51232; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51233; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51241; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51246; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51234; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51237; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51238; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51244; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51239; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51242; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51245; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51236; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51235; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51240; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51203; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51202; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51272; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51290; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51271; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51291; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51287; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51314; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51274; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51275; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51270; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51269; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51289; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51313; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51288; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51268; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50242; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51282; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102995; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51283; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51285; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51286; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51215; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51284; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51204; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51281; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51277; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51279; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51280; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51254; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51263; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51253; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51261; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51262; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 103026; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102985; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51315; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102983; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51307; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51316; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51260; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51308; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51317; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51205; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51276; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51278; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51318; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102976; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 50212; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51252; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51319; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 62483; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51257; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51309; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51251; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 103018; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51310; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51214; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 102965; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51256; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51149; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51265; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51267; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51305; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51306; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51266; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51258; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51264; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51311; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51213; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51259; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51206; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51212; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51312; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51211; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51292; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51293; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51294; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51295; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51296; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51207; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51208; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 103005; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51209; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51297; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 103023; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51210; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51304; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51298; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51303; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51299; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51180; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51181; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51300; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51179; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51301; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51100; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51182; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51178; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51191; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51183; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51189; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51177; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51190; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51153; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51101; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51150; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51102; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51152; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51151; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51174; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51145; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51103; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51188; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51144; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51143; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51173; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51175; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51147; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51148; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51187; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51142; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51176; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51184; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51154; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51141; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51140; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51155; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51158; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51156; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51157; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51185; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51139; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51134; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51135; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51138; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51104; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51159; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51186; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51105; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51133; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51106; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51137; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51107; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51114; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51108; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51109; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51136; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51124; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51110; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51123; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51127; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51128; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51120; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51118; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51126; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51125; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51122; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51113; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51121; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51111; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51112; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51132; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51119; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51117; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51131; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51130; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51115; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51116; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51160; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51161; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51162; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51163; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51164; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51165; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51172; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51166; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51167; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51168; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51170; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51169; 
DELETE FROM pscis.pscis_assessment_svw WHERE stream_crossing_id = 51171; 
